Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "TomcatServer"
    vb.memory = 1024
    vb.cpus = 1
end
config.vm.hostname = "TomcatServer"
config.vm.network :private_network, ip: "192.168.56.20"
config.vm.provision "ansible_local" do |ansible|
  ansible.verbose = "v"
  ansible.playbook = "tomcatinstall.yml"
end
end
