insert into PLAYERS (PLAYER_ID,PLAYER_TEAM,PLAYER_NAME,PLAYER_COUNTRY,PLAYER_DOB,PLAYER_ROLE,
PLAYER_BATTINGSTYLE,PLAYER_BOWLINGSTYLE,PLAYER_HEIGHT,PLAYER_AUCTIONPRICE)
values(10001,'SRH','David Warner','AUS','1986-10-27','Batsman' ,
'Left-Handed Bat','Right-Arm Bowl','170m','Retained');
insert into PLAYERS(PLAYER_Id,PLAYER_TEAM,PLAYER_NAME,PLAYER_COUNTRY,PLAYER_DOB,PLAYER_ROLE,
PLAYER_BATTINGSTYLE,PLAYER_BOWLINGSTYLE,PLAYER_HEIGHT,PLAYER_AUCTIONPRICE)
values(10002,'RCB','Virat Kohli','IND','1988-11-05','Batsman' ,
'Right-Handed Bat','Right-Arm Medium Pace','172m','Retained');
insert into PLAYERS(PLAYER_Id,PLAYER_TEAM,PLAYER_NAME,PLAYER_COUNTRY,PLAYER_DOB,PLAYER_ROLE,
PLAYER_BATTINGSTYLE,PLAYER_BOWLINGSTYLE,PLAYER_HEIGHT,PLAYER_AUCTIONPRICE)
values(10003,'Not Sold In Auction','Joe Root','ENG','1990-12-30','Batsman',
'Right-Handed Bat','Right-Arm Bowl','174m','Retained');
insert into PLAYERS(PLAYER_Id,PLAYER_TEAM,PLAYER_NAME,PLAYER_COUNTRY,PLAYER_DOB,PLAYER_ROLE,
PLAYER_BATTINGSTYLE,PLAYER_BOWLINGSTYLE,PLAYER_HEIGHT,PLAYER_AUCTIONPRICE)
values(10004,'SRH','Alex Hales','ENG','1990-12-31','Batsman',
'Right-Handed Bat','Right-Arm Offbreak','181m','Auction');



INSERT INTO users VALUES (1,1,'$2a$10$iFolDdAquu/qSclfNDiBK.GFpO0gUBAsCilygHuCy6pUWVd.4ZK8G', 'admin','ADMIN');
