pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                rtMavenRun (
                    tool: maven, // Tool name from Jenkins configuration
                    pom: 'PlayerDetails/pom.xml',
                    goals: 'clean install'
                )
            }
        } 
    }
}
