pipeline {
    agent any
    stages {
        stage('Example Build') {
            steps {
                agent any
                echo 'Hello, Maven'
                sh 'mvn clean install'
            }
        }
        
    }
}
