insert into TEAM_DETAILS (TEAM_ID,TEAM_NAME,TEAM_COUNTRY,TEAM_LASTYEARPOSITION,TEAM_OWNER,TEAM_COACH,TEAM_CAPTAIN,TEAM_VENUE,PLAYER_TEAM,PLAYER_NAME)
values (10001,'SRH','India','2','Sun Network','Tom Moody','David Warner','HYD','SRH','David Warner');
insert into TEAM_DETAILS (TEAM_ID,TEAM_NAME,TEAM_COUNTRY,TEAM_LASTYEARPOSITION,TEAM_OWNER,TEAM_COACH,TEAM_CAPTAIN,TEAM_VENUE,PLAYER_TEAM,PLAYER_NAME)
values (10002,'CSK','India','1','India Cements','Stefen Fleming','Dhoni','Chennai','CSK','DHONI');
insert into TEAM_DETAILS (TEAM_ID,TEAM_NAME,TEAM_COUNTRY,TEAM_LASTYEARPOSITION,TEAM_OWNER,TEAM_COACH,TEAM_CAPTAIN,TEAM_VENUE,PLAYER_TEAM,PLAYER_NAME)
values (10003,'RCB','India','6','UB','Gary Kirsten','KOHLI','Bengaluru','RCB','KOHLI');
insert into TEAM_DETAILS (TEAM_ID,TEAM_NAME,TEAM_COUNTRY,TEAM_LASTYEARPOSITION,TEAM_OWNER,TEAM_COACH,TEAM_CAPTAIN,TEAM_VENUE,PLAYER_TEAM,PLAYER_NAME)
values (10004,'DC','India','3','GMR','Ricky Ponting','IYER','Delhi','DDC','IYER');
