insert into TEAM_DETAILS (TEAM_ID,TEAM_NAME,TEAM_COUNTRY,TEAM_LASTYEARPOSITION,TEAM_OWNER,TEAM_COACH,TEAM_CAPTAIN,TEAM_VENUE)
values (10001,'SRH','India','2','Sun Network','Tom Moody','David Warner','HYD');
insert into TEAM_DETAILS (TEAM_ID,TEAM_NAME,TEAM_COUNTRY,TEAM_LASTYEARPOSITION,TEAM_OWNER,TEAM_COACH,TEAM_CAPTAIN,TEAM_VENUE)
values (10002,'CSK','India','1','India Cements','Stefen Fleming','David Warner','Chennai');
insert into TEAM_DETAILS (TEAM_ID,TEAM_NAME,TEAM_COUNTRY,TEAM_LASTYEARPOSITION,TEAM_OWNER,TEAM_COACH,TEAM_CAPTAIN,TEAM_VENUE)
values (10003,'RCB','India','6','UB','Tom Moody','Gary Kirsten','Bengaluru');
insert into TEAM_DETAILS (TEAM_ID,TEAM_NAME,TEAM_COUNTRY,TEAM_LASTYEARPOSITION,TEAM_OWNER,TEAM_COACH,TEAM_CAPTAIN,TEAM_VENUE)
values (10004,'DC','India','3','GMR','Tom Moody','Ricky Ponting','Delhi');
